export const majorsData = [
    { value: '인문융합자율학부', label: '인문융합자율학부' },
    { value: '사회융합자율학부', label: '사회융합자율학부' },
    { value: '미디어컨텐츠융합자율학부', label: '미디어컨텐츠융합자율학부' },
    { value: 'IT융합자율학부', label: 'IT융합자율학부' },
    { value: '기독교문화전공', label: '기독교문화전공' },
    { value: '일어일본학전공', label: '일어일본학전공' },
    { value: '중어중국학전공', label: '중어중국학전공' },
    { value: '사회복지학전공', label: '사회복지학전공' },
    { value: '사회학전공', label: '사회학전공' },
    { value: '경제학전공', label: '경제학전공' },
    { value: '정치학전공', label: '정치학전공' },
    { value: '경영학전공', label: '경영학전공' },
    { value: '신문방송학전공', label: '신문방송학전공' },
    { value: '디지털컨텐츠전공', label: '디지털컨텐츠전공' },
    { value: '컴퓨터공학전공', label: '컴퓨터공학전공' },
    { value: '소프트웨어공학전공', label: '소프트웨어공학전공' },
    { value: '정보통신공학전공', label: '정보통신공학전공' },
];

export const majorsData2 = [
    { value: '없음', label: '없음' },
    { value: '기독교문화전공', label: '기독교문화전공' },
    { value: '일어일본학전공', label: '일어일본학전공' },
    { value: '중어중국학전공', label: '중어중국학전공' },
    { value: '사회복지학전공', label: '사회복지학전공' },
    { value: '사회학전공', label: '사회학전공' },
    { value: '경제학전공', label: '경제학전공' },
    { value: '정치학전공', label: '정치학전공' },
    { value: '경영학전공', label: '경영학전공' },
    { value: '신문방송학전공', label: '신문방송학전공' },
    { value: '디지털컨텐츠전공', label: '디지털컨텐츠전공' },
    { value: '컴퓨터공학전공', label: '컴퓨터공학전공' },
    { value: '소프트웨어공학전공', label: '소프트웨어공학전공' },
    { value: '정보통신공학전공', label: '정보통신공학전공' },
];
